Added Vagrantfile to project with virtualbox config option allowing for symlinks on Windows hosts. Tip: I order for symlinks to work in Windows host, Vagrant should run as Administrator.
Added module "underscore" to pachage.json, because is used in the
backend (users_controller.js), but was installed only by bower and
"Error: Cannot find module 'underscore'" exception was thrown by nodejs.

Added instructions for Vagrant to README.md.